###############################################################################
## Application properties
###############################################################################
spring.profiles:
  group:
    local: local-profile,common-profile
    dev: dev-profile,common-profile
    prod: prod-profile,common-profile
  default: prod
  active: prod

  datasource:
    rpa: true
  name: "포탈"
  version: "0.1"
  storage-mode: local
  ext.enable: false

jasypt:
  db-prop:
    password: "rpago!23"
    algorithm: "PBEWITHHMACSHA512ANDAES_256"
    key-obtention-iterations: 1000
    poolSize: 1
    provider-name: "SunJCE"
#    salt-generator: "org.jasypt.salt.RandomSaltGenerator"
    string-output-type: "base64"

---
###############################################################################
## common-profile
###############################################################################
spring.config.activate.on-profile: common-profile

# thymeleaf view
spring.thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  view-names: thymeleaf/*

# jsp view
spring.mvc.view:
  prefix: /WEB-INF/
  suffix: .jsp

# datasource
spring.datasource.hikari:
  primary:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://192.168.20.52:4406/portal?serverTimezone=UTC&characterEncoding=utf8
    username: admin
    password: dbadmin!23
    maximum-pool-size: 50
    max-lifetime: 30000
    connection-timeout: 0
    transaction-isolation: TRANSACTION_READ_UNCOMMITTED
  rpa:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://192.168.20.51:4406/rpa?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: rpago!23
    maximum-pool-size: 50
    max-lifetime: 30000
    connection-timeout: 0
    transaction-isolation: TRANSACTION_READ_UNCOMMITTED

# mybatis
mybatis:
  primary:
    mapper-config-location: classpath:mapper/primary-mybatis-config.xml
    mapper-locations: classpath:mapper/primary/*.xml
    mapper-scan-base-packages: portal.mapper.primary
  rpa:
    mapper-config-location: classpath:mapper/rpa-mybatis-config.xml
    mapper-locations: classpath:mapper/rpa/*.xml
    mapper-scan-base-packages: portal.mapper.rpa

spring.output.ansi.enabled: always

logging:
  level:
    '[portal]': debug
    jdbc:
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: off
      resultsettable: off
      connection: off

springdoc:
  packages-to-scan: portal
  swagger-ui:
    tryItOutEnabled: true
    displayOperationId: true
    displayRequestDuration: true
    urls-primary-name: "dev API"
    urls:
      - name : "dev API"
        url : "http://192.168.50.98:8080/portal/v3/api-docs"
      - name : "local API"
        url : "/v3/api-docs"


portal:
  whitelist:
    - "/"
    - "/error"
    - "/error/**"
    - "/index.html"
    - "/favicon.ico"
    - "/hi-works.png"
    - "/public/**"
    - "/frontend/**"
    - "/swagger-ui.html"
    - "/swagger-ui/**"
    - "/v3/api-docs/**"

---
###############################################################################
## local-profile
###############################################################################
spring.config.activate.on-profile: local-profile
spring.output.ansi.enabled: always
spring:
  devtools:
#    restart:
#      enabled: true
    livereload:
      enabled: true

server:
  servlet:
    jsp:
      init-parameters:
        development: true

#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#spring.datasource.hikari:
#  primary:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    jdbc-url: jdbc:log4jdbc:mariadb://localhost:4406/portal?serverTimezone=UTC&characterEncoding=utf8
#    username: root
#    password: rpago!23
#    maximum-pool-size: 50
#    max-lifetime: 30000
#    connection-timeout: 0
#    transaction-isolation: TRANSACTION_READ_UNCOMMITTED

logging:
  level:
    '[portal]': debug
    jdbc:
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: off
      resultsettable: off
      connection: off

springdoc:
  swagger-ui:
    urls-primary-name: "local API"


---
###############################################################################
## dev-profile
###############################################################################
spring.config.activate.on-profile: dev-profile

spring.output.ansi.enabled: always

logging:
  level:
    '[portal]': debug
    jdbc:
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: off
      resultsettable: off
      connection: off

