###############################################################################
## Application properties
###############################################################################
spring:
  profiles:
    group:
      local: local-profile,common-profile
      dev: dev-profile,common-profile
      prod: prod-profile,common-profile
    default: prod
    active: prod

portal:
  datasource:
    rpa: true
  name: "포탈"
  version: "0.1"
  storage-mode: local
  publicPaths:
    - "/"
    - "/error"
    - "/error/**"
    - "/index.html"
    - "/favicon.ico"
    - "/hi-works.png"
    - "/public/**"
    - "/frontend/**"
    - "/swagger-ui.html"
    - "/swagger-ui/**"
    - "/v3/api-docs/**"
    - "/h2-console/**"
  ip-block:
    enable: false
    blacklist:
      - "192.168.20.51"
    whitelist:
      - "192.168.20.52"
      - "127.0.0.1"
      - "0:0:0:0:0:0:0:0:1"
      - "::1"
  ocr-base-url: "http://dev.hyperinfo.co.kr"
  ocr-api-key: "SNOCR-3de238b328cf4bde9a73e6adc693918b"

server:
  address: 0.0.0.0
  servlet:
    session:
      persistent: false

---
###############################################################################
## common-profile
###############################################################################
spring.config.activate.on-profile: common-profile

# thymeleaf view
spring.thymeleaf:
  cache: true
  prefix: classpath:/templates/
  suffix: .html
  view-names: thymeleaf/*

# jsp view
spring.mvc.view:
  prefix: /WEB-INF/
  suffix: .jsp

# datasource
spring.datasource.hikari:
  primary:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://192.168.20.52:4406/portal?serverTimezone=UTC&characterEncoding=utf8
    username: admin
    password: dbadmin!23
    maximum-pool-size: 50
    max-lifetime: 30000
    connection-timeout: 0
    transaction-isolation: TRANSACTION_READ_UNCOMMITTED
  rpa:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://192.168.20.51:4406/rpa?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: rpago!23
    maximum-pool-size: 50
    max-lifetime: 30000
    connection-timeout: 0
    transaction-isolation: TRANSACTION_READ_UNCOMMITTED

# mybatis
mybatis:
  primary:
    mapper-config-location: classpath:mapper/primary-mybatis-config.xml
    mapper-locations: classpath:mapper/primary/*.xml
    mapper-scan-base-packages: portal.mapper.primary
  rpa:
    mapper-config-location: classpath:mapper/rpa-mybatis-config.xml
    mapper-locations: classpath:mapper/rpa/*.xml
    mapper-scan-base-packages: portal.mapper.rpa

spring.output.ansi.enabled: always

logging:
  level:
    '[portal]': debug
    jdbc:
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: off
      resultsettable: off
      connection: off

#springdoc:
#  packages-to-scan: portal
#  swagger-ui:
#    tryItOutEnabled: true
#    displayOperationId: true
#    displayRequestDuration: true
#    urls-primary-name: "dev API"
#    urls:
#      - name : "dev API"
#        url : "http://192.168.50.98:8080/portal/v3/api-docs"
#      - name : "local API"
#        url : "/v3/api-docs"

---
###############################################################################
## local-profile
###############################################################################
spring.config.activate.on-profile: local-profile
spring.output.ansi.enabled: always
spring:
  devtools:
#    restart:
#      enabled: true
    livereload:
      enabled: true

spring.thymeleaf.cache: false

server:
  servlet:
    jsp:
      init-parameters:
        development: true

spring.datasource.hikari:
  minimum-idle: 10
  maximum-pool-size: 30
  housekeeping-period: 30000
  primary:
    driver-class-name: org.h2.Driver
    jdbc-url: 'jdbc:h2:./db/primary'
#    username: admin        # H2 DB 접속 ID (사용자 지정)
#    password: password        # H2 DB 접속 PW (사용자 지정)
  rpa:
    driver-class-name: org.h2.Driver
    jdbc-url: 'jdbc:h2:./db/rpa'
#    username: admin        # H2 DB 접속 ID (사용자 지정)
#    password: password        # H2 DB 접속 PW (사용자 지정)

logging:
  level:
    '[portal]': debug
    jdbc:
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: off
      resultsettable: off
      connection: off
    org:
      springframework:
        web: DEBUG

---
###############################################################################
## dev-profile
###############################################################################
spring.config.activate.on-profile: dev-profile

spring.output.ansi.enabled: always

logging:
  level:
    '[portal]': debug
    jdbc:
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: off
      resultsettable: off
      connection: off
